// <auto-generated />
using System;
using DeluxeNET.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeluxeNET.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420071250_settingsAddition")]
    partial class settingsAddition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DeluxeNET.Data.CachedLogin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("accountId")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "accountId");

                    b.Property<DateTime>("lastLoginTime")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "lastLoginTime");

                    b.Property<int>("platform")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "platform");

                    b.Property<string>("platformId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "platformId");

                    b.Property<bool>("requirePassword")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "requirePassword");

                    b.HasKey("Id");

                    b.ToTable("CachedLogins");
                });

            modelBuilder.Entity("DeluxeNET.Data.account", b =>
                {
                    b.Property<long>("accountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "accountId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("accountId"));

                    b.Property<string>("bannerImage")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "bannerImage");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("displayName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "displayName");

                    b.Property<int>("identityFlags")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "identityFlags");

                    b.Property<bool>("isJunior")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "isJunior");

                    b.Property<bool>("isMetaPlatformBlocked")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "isMetaPlatformBlocked");

                    b.Property<int>("personalPronouns")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "personalPronouns");

                    b.Property<int>("platforms")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "platforms");

                    b.Property<string>("profileImage")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "profileImage");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "username");

                    b.HasKey("accountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("DeluxeNET.Data.setting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "Key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "Value");

                    b.Property<long>("accountId")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "accountId");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
