// <auto-generated />
using System;
using DeluxeNET.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeluxeNET.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419212506_CachedLoginsAdd")]
    partial class CachedLoginsAdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DeluxeNET.Data.CachedLogin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("accountId")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "accountId");

                    b.Property<DateTime>("lastLoginTime")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "lastLoginTime");

                    b.Property<int>("platform")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "platform");

                    b.Property<string>("platformId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "platformId");

                    b.Property<bool>("requirePassword")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "requirePassword");

                    b.HasKey("Id");

                    b.ToTable("CachedLogins");
                });
#pragma warning restore 612, 618
        }
    }
}
