// <auto-generated />
using System;
using DeluxeNET.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeluxeNET.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DeluxeNET.Data.CachedLogin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("accountId")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "accountId");

                    b.Property<DateTime>("lastLoginTime")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "lastLoginTime");

                    b.Property<int>("platform")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "platform");

                    b.Property<string>("platformId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "platformId");

                    b.Property<bool>("requirePassword")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "requirePassword");

                    b.HasKey("Id");

                    b.ToTable("CachedLogins");
                });

            modelBuilder.Entity("DeluxeNET.Data.Heartbeat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DeviceClass")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastOnline")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RoomInstanceId")
                        .HasColumnType("bigint");

                    b.Property<int>("StatusVisibility")
                        .HasColumnType("int");

                    b.Property<int>("VrMovementMode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomInstanceId");

                    b.ToTable("Heartbeats");
                });

            modelBuilder.Entity("DeluxeNET.Data.Room", b =>
                {
                    b.Property<long>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "RoomId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("RoomId"));

                    b.Property<int>("Accessibility")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "Accessibility");

                    b.Property<bool>("CloningAllowed")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "CloningAllowed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "CreatedAt");

                    b.Property<int>("CreatorAccountId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "CreatorAccountId");

                    b.Property<string>("CustomWarning")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "CustomWarning");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "Description");

                    b.Property<bool>("DisableMicAutoMute")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "DisableMicAutoMute");

                    b.Property<bool>("DisableRoomComments")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "DisableRoomComments");

                    b.Property<bool>("EncryptVoiceChat")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "EncryptVoiceChat");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "ImageName");

                    b.Property<bool>("IsDeveloperOwned")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "IsDeveloperOwned");

                    b.Property<bool>("IsDorm")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "IsDorm");

                    b.Property<bool>("IsRRO")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "IsRRO");

                    b.Property<bool>("LoadScreenLocked")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "LoadScreenLocked");

                    b.Property<int>("MaxPlayerCalculationMode")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "MaxPlayerCalculationMode");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "MaxPlayers");

                    b.Property<int>("MinLevel")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "MinLevel");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "Name");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "State");

                    b.Property<bool>("SupportsJuniors")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "SupportsJuniors");

                    b.Property<bool>("SupportsLevelVoting")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "SupportsLevelVoting");

                    b.Property<bool>("SupportsMobile")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "SupportsMobile");

                    b.Property<bool>("SupportsQuest2")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "SupportsQuest2");

                    b.Property<bool>("SupportsScreens")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "SupportsScreens");

                    b.Property<bool>("SupportsTeleportVR")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "SupportsTeleportVR");

                    b.Property<bool>("SupportsVRLow")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "SupportsVRLow");

                    b.Property<bool>("SupportsWalkVR")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "SupportsWalkVR");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "Tags");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "Version");

                    b.Property<int>("WarningMask")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "WarningMask");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("DeluxeNET.Data.RoomInstance", b =>
                {
                    b.Property<long>("RoomInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("RoomInstanceId"));

                    b.Property<bool>("IsFull")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsInProgress")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MatchmakingPolicy")
                        .HasColumnType("int");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhotonRegion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhotonRegionId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhotonRoomId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<int>("RoomInstanceType")
                        .HasColumnType("int");

                    b.Property<long>("SubRoomId")
                        .HasColumnType("bigint");

                    b.HasKey("RoomInstanceId");

                    b.HasIndex("Name");

                    b.ToTable("RoomInstances");
                });

            modelBuilder.Entity("DeluxeNET.Data.RoomRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "AccountId");

                    b.Property<int>("InvitedRole")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "InvitedRole");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "Role");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "RoomId");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomRoles");

                    b.HasAnnotation("Relational:JsonPropertyName", "Roles");
                });

            modelBuilder.Entity("DeluxeNET.Data.RoomStats", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CheerCount")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "CheerCount");

                    b.Property<int>("FavoriteCount")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "FavoriteCount");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "RoomId");

                    b.Property<int>("VisitCount")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "VisitCount");

                    b.Property<int>("VisitorCount")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "VisitorCount");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("RoomStats");

                    b.HasAnnotation("Relational:JsonPropertyName", "Stats");
                });

            modelBuilder.Entity("DeluxeNET.Data.SubRoom", b =>
                {
                    b.Property<int>("SubRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "SubRoomId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SubRoomId"));

                    b.Property<int>("Accessibility")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "Accessibility");

                    b.Property<bool>("IsSandbox")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "IsSandbox");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "MaxPlayers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "Name");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "RoomId");

                    b.Property<string>("UnitySceneId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "UnitySceneId");

                    b.HasKey("SubRoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("SubRooms");

                    b.HasAnnotation("Relational:JsonPropertyName", "SubRooms");
                });

            modelBuilder.Entity("DeluxeNET.Data.SubRoomSave", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "CreatedAt");

                    b.Property<string>("DataBlob")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "DataBlob");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "Description");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "RoomId");

                    b.Property<int>("SavedByAccountId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "SavedByAccountId");

                    b.Property<int>("SubRoomDataSaveId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "SubRoomDataSaveId");

                    b.Property<int>("SubRoomId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "SubRoomId");

                    b.Property<int?>("SubRoomId1")
                        .HasColumnType("int");

                    b.Property<string>("UnityAssetId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "UnityAssetId");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("SubRoomId")
                        .IsUnique();

                    b.HasIndex("SubRoomId1");

                    b.ToTable("SubRoomSaves");

                    b.HasAnnotation("Relational:JsonPropertyName", "CurrentSave");
                });

            modelBuilder.Entity("DeluxeNET.Data.account", b =>
                {
                    b.Property<long>("accountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "accountId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("accountId"));

                    b.Property<string>("bannerImage")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "bannerImage");

                    b.Property<string>("bio")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "bio");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("displayName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "displayName");

                    b.Property<int>("identityFlags")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "identityFlags");

                    b.Property<bool>("isJunior")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "isJunior");

                    b.Property<bool>("isMetaPlatformBlocked")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "isMetaPlatformBlocked");

                    b.Property<int>("personalPronouns")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "personalPronouns");

                    b.Property<int>("platforms")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "platforms");

                    b.Property<string>("profileImage")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "profileImage");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "username");

                    b.HasKey("accountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("DeluxeNET.Data.avatar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("FaceFeatures")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "FaceFeatures");

                    b.Property<string>("HairColor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "HairColor");

                    b.Property<string>("OutfitSelections")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "OutfitSelections");

                    b.Property<string>("SkinColor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "SkinColor");

                    b.Property<long?>("accountId")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "accountId");

                    b.HasKey("Id");

                    b.ToTable("Avatars");
                });

            modelBuilder.Entity("DeluxeNET.Data.progression", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "Level");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "PlayerId");

                    b.Property<int>("XP")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "XP");

                    b.HasKey("Id");

                    b.ToTable("Progressions");
                });

            modelBuilder.Entity("DeluxeNET.Data.reputation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CheerCreative")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "CheerCreative");

                    b.Property<int>("CheerCredit")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "CheerCredit");

                    b.Property<int>("CheerGeneral")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "CheerGeneral");

                    b.Property<int>("CheerGreatHost")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "CheerGreatHost");

                    b.Property<int>("CheerHelpful")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "CheerHelpful");

                    b.Property<int>("CheerSportsman")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "CheerSportsman");

                    b.Property<bool>("IsCheerful")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "IsCheerful");

                    b.Property<float>("Noteriety")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "Noteriety");

                    b.Property<int>("SelectedCheer")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "SelectedCheer");

                    b.Property<long>("accountId")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "accountId");

                    b.HasKey("Id");

                    b.ToTable("Reputations");
                });

            modelBuilder.Entity("DeluxeNET.Data.setting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "Key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "Value");

                    b.Property<long?>("accountId")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "accountId");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("DeluxeNET.Data.Heartbeat", b =>
                {
                    b.HasOne("DeluxeNET.Data.RoomInstance", "RoomInstance")
                        .WithMany("Heartbeats")
                        .HasForeignKey("RoomInstanceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RoomInstance");
                });

            modelBuilder.Entity("DeluxeNET.Data.RoomRole", b =>
                {
                    b.HasOne("DeluxeNET.Data.Room", "Room")
                        .WithMany("Roles")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DeluxeNET.Data.RoomStats", b =>
                {
                    b.HasOne("DeluxeNET.Data.Room", "Room")
                        .WithOne("Stats")
                        .HasForeignKey("DeluxeNET.Data.RoomStats", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DeluxeNET.Data.SubRoom", b =>
                {
                    b.HasOne("DeluxeNET.Data.Room", "Room")
                        .WithMany("SubRooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DeluxeNET.Data.SubRoomSave", b =>
                {
                    b.HasOne("DeluxeNET.Data.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeluxeNET.Data.SubRoom", "SubRoom")
                        .WithOne("CurrentSave")
                        .HasForeignKey("DeluxeNET.Data.SubRoomSave", "SubRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeluxeNET.Data.SubRoom", null)
                        .WithMany("SubRoomSaves")
                        .HasForeignKey("SubRoomId1");

                    b.Navigation("Room");

                    b.Navigation("SubRoom");
                });

            modelBuilder.Entity("DeluxeNET.Data.Room", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("SubRooms");
                });

            modelBuilder.Entity("DeluxeNET.Data.RoomInstance", b =>
                {
                    b.Navigation("Heartbeats");
                });

            modelBuilder.Entity("DeluxeNET.Data.SubRoom", b =>
                {
                    b.Navigation("CurrentSave")
                        .IsRequired();

                    b.Navigation("SubRoomSaves");
                });
#pragma warning restore 612, 618
        }
    }
}
